FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# IMPORTANT: this copies metrics/ and everything else into /app
COPY . .

WORKDIR /app/streamlit

ENV API_URL=http://api:8000

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
